global:
  opsgenie_api_key: 'dcbbb229-d58f-41cf-8569-114eaa3d7b2d'

route:
  group_by:
    - alertname
    - env
    - instance
    - type
    - group
    - job
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 30m
  receiver: opsgenie

receivers:
  - name: opsgenie
    opsgenie_configs:
      - message: '[Prometheus][{{ .CommonLabels.severity }}]: {{ .CommonLabels.level }} Host {{ .CommonLabels.Hostname }} {{.GroupLabels.alertname}}'
        priority: '{{ .CommonLabels.priority }}'
        tags: '{{ .CommonLabels.ApplicationName }},
          {{ .CommonLabels.kind }},
          {{ .CommonLabels.type }},
          {{ .CommonLabels.job }},
          {{ .CommonLabels.ApplicationRole }},
          {{ .CommonLabels.Environment }},
          {{ .CommonLabels.ApplicationOwner }}'
        description: |-
          {{ if gt (len .Alerts.Firing) 0 -}}
          Details:
          {{ range .Alerts.Firing }}
          {{ range .Annotations.SortedPairs }}  {{ .Name }} = {{ .Value }}
          {{ end }}
          Source: {{ .GeneratorURL }}
          {{ end }}
          {{- end }}
          {{ if gt (len .Alerts.Resolved) 0 -}}
          Resolved:
          {{ range .Alerts.Resolved }}
          Details:
          {{ range .Annotations.SortedPairs }}   - {{ .Name }} = {{ .Value }}
          {{ end }}   Source: {{ .GeneratorURL }}
          {{ end }}
          {{- end }}
        details:
          Type: '{{ .CommonLabels.job }}'
          Hostname: '{{ .CommonLabels.Hostname }}'
          Instance: '{{ .CommonLabels.instance }}'
          ApplicationName: '{{ .CommonLabels.ApplicationName }}'
          ApplicationOwner: '{{ .CommonLabels.ApplicationOwner }}'
          Environment: '{{ .CommonLabels.Environment }}'
          ApplicationRole: '{{ .CommonLabels.ApplicationRole }}'