groups:
- name: Linux告警规则
  rules:
    - alert: 磁盘inode使用率超过90%
      expr: (1- node_filesystem_files_free / node_filesystem_files) * 100 >= 90
      for: 1m
      labels:
        severity: High
      annotations:
        summary: "服务器{{ $labels.hostname }}磁盘inode使用率告警"
        description: "\n  服务器{{ $labels.hostname }}磁盘使用率告警 \n  服务器IP: {{ $labels.instance }} \n  所属应用：{{ $labels.APP }} \n  应用负责人：{{ $labels.manager }} \n  磁盘inode使用率超过90%"
        value: "{{ $value }}%"
    - alert: 磁盘IO延迟超过100ms
      expr: (rate(node_disk_read_time_seconds_total[1m]) / rate(node_disk_reads_completed_total[1m]) > 0.1 and rate(node_disk_reads_completed_total[1m]) > 0) or (rate(node_disk_write_time_seconds_total[1m]) / rate(node_disk_writes_completed_total[1m]) > 0.1 and rate(node_disk_writes_completed_total[1m]) > 0)
      for: 1m
      labels:
        severity: Low
      annotations:
        summary: "服务器{{ $labels.hostname }}磁盘IO延迟告警"
        description: "\n  服务器{{ $labels.hostname }}磁盘使用率告警 \n  服务器IP: {{ $labels.instance }} \n  所属应用：{{ $labels.APP }} \n  应用负责人：{{ $labels.manager }} \n  磁盘IO延迟超过100ms"
        value: "{{ $value }}%"

    - alert: CPU中断告警
      expr: irate(node_intr_total[5m]) > 50000
      for: 1m
      labels:
        severity: Informational
      annotations:
        summary: "服务器{{ $labels.hostname }}CPU中断告警"
        description: "\n  服务器{{ $labels.hostname }}磁盘使用率告警 \n  服务器IP: {{ $labels.instance }} \n  所属应用：{{ $labels.APP }} \n  应用负责人：{{ $labels.manager }} \n  CPU中断告警"
        value: "{{ $value }}%"
    - alert: CPU iowait告警
      expr: avg by (instance) (rate(node_cpu_seconds_total{mode="iowait"}[5m])) * 100 > 20
      for: 1m
      labels:
        severity: Moderate
      annotations:
        summary: "服务器{{ $labels.hostname }}CPU iowait告警"
        description: "\n  服务器{{ $labels.hostname }}磁盘使用率告警 \n  服务器IP: {{ $labels.instance }} \n  所属应用：{{ $labels.APP }} \n  应用负责人：{{ $labels.manager }} \n  CPU iowait告警"
        value: "{{ $value }}%"
    - alert: 内存占用率
      expr: (1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100 > 80
      for: 1m
      labels:
        severity: Moderate
      annotations:
        summary: "服务器{{ $labels.hostname }}内存使用率告警"
        description: "\n  服务器{{ $labels.hostname }}内存使用率告警 \n  服务器IP: {{ $labels.instance }} \n  所属应用：{{ $labels.APP }} \n  应用负责人：{{ $labels.manager }} \n  内存占用率"
        value: "{{ $value }}%"
    - alert: 缓存使用率
      expr: (1- node_memory_SwapFree_bytes / node_memory_SwapTotal_bytes) * 100 > 49
      for: 1m
      labels:
        severity: Low
      annotations:
        summary: "服务器{{ $labels.hostname }}SWAP内存使用率告警"
        description: "\n  服务器{{ $labels.hostname }}SWAP内存使用率告警 \n  服务器IP: {{ $labels.instance }} \n  所属应用：{{ $labels.APP }} \n  应用负责人：{{ $labels.manager }} \n  缓存使用率"
        value: "{{ $value }}%"
    - alert: OOM统计
      expr: increase(node_vmstat_oom_kill[1m]) > 0
      for: 1m
      labels:
        severity: High
      annotations:
        summary: "服务器{{ $labels.hostname }}内存OOM告警"
        description: "\n  服务器{{ $labels.hostname }}OOM使用率告警 \n  服务器IP: {{ $labels.instance }} \n  所属应用：{{ $labels.APP }} \n  应用负责人：{{ $labels.manager }} \n  OOM统计"
        value: "{{ $value }}%"
    - alert: 主机发生重启
      expr: (time() - node_boot_time_seconds)/60 < 10
      for: 1m
      labels:
        severity: High
      annotations:
        summary: "服务器{{ $labels.hostname }}发生重启"
        description: "\n  服务器{{ $labels.hostname }}主机状态告警 \n  服务器IP: {{ $labels.instance }} \n  所属应用：{{ $labels.APP }} \n  应用负责人：{{ $labels.manager }} \n  主机发生重启"
        value: "{{ $value }}%"
    - alert: 系统时间不准确
      expr: (time() - node_time_seconds) >= 60
      for: 1m
      labels:
        severity: High
      annotations:
        summary: "服务器{{ $labels.hostname }}系统时间不准确"
        description: "\n  服务器{{ $labels.hostname }}系统时间告警 \n  服务器IP: {{ $labels.instance }} \n  所属应用：{{ $labels.APP }} \n  应用负责人：{{ $labels.manager }} \n  系统时间不准确"
        value: "{{ $value }}%"
    - alert: 网络利用率超过
      expr: sum by (instance) (rate(node_network_receive_bytes_total[2m])) / 1024 / 1024 > 100 or sum by (instance) (rate(node_network_transmit_bytes_total[2m])) / 1024 / 1024 > 100
      for: 1m
      labels:
        severity: Informational
      annotations:
        summary: "服务器{{ $labels.hostname }}网络利用率超过100Mbps"
        description: "\n  服务器{{ $labels.hostname }}网络使用率告警 \n  服务器IP: {{ $labels.instance }} \n  所属应用：{{ $labels.APP }} \n  应用负责人：{{ $labels.manager }} \n  网络利用率超过"
        value: "{{ $value }}%"
    - alert: 网络接口错误率超过阈值
      expr: sum by (instance) (rate(node_network_receive_errs_total[2m])) / 1024 / 1024 > 0 or sum by (instance) (rate(node_network_transmit_errs_total[2m])) / 1024 / 1024 > 0
      for: 1m
      labels:
        severity: Moderate
      annotations:
        summary: "服务器{{ $labels.hostname }}网络接口出现错误包"
        description: "\n  服务器{{ $labels.hostname }}网络接口错误率告警 \n  服务器IP: {{ $labels.instance }} \n  所属应用：{{ $labels.APP }} \n  应用负责人：{{ $labels.manager }} \n  网络接口错误率超过阈值"
        value: "{{ $value }}%"
    - alert: 网络接口发生变化
      expr: sum by(instance) (changes(node_network_info[10m])) > 1
      for: 1m
      labels:
        severity: High
      annotations:
        summary: "服务器{{ $labels.hostname }}网络接口发生变化"
        description: "\n  服务器{{ $labels.hostname }}网络接口状态告警 \n  服务器IP: {{ $labels.instance }} \n  所属应用：{{ $labels.APP }} \n  应用负责人：{{ $labels.manager }} \n  网络接口发生变化"
        value: "{{ $value }}%"
    - alert: TCP 连接数超过阈值
      expr: node_sockstat_TCP_inuse >= 500 or node_sockstat_TCP6_inuse >= 500
      for: 1m
      labels:
        severity: Informational
      annotations:
        summary: "服务器{{ $labels.hostname }}TCP连接数超过500"
        description: "\n  服务器{{ $labels.hostname }}TCP连接数告警 \n  服务器IP: {{ $labels.instance }} \n  所属应用：{{ $labels.APP }} \n  应用负责人：{{ $labels.manager }} \n  TCP 连接数超过阈值"
        value: "{{ $value }}%"
    - alert: 系统时区错误
      expr: sum by(instance) (node_time_zone_offset_seconds{time_zone="CST"}) != 28800
      for: 1m
      labels:
        severity: High
      annotations:
        summary: "服务器{{ $labels.hostname }}系统时区错误"
        description: "\n  服务器{{ $labels.hostname }}系统时区告警 \n  服务器IP: {{ $labels.instance }} \n  所属应用：{{ $labels.APP }} \n  应用负责人：{{ $labels.manager }} \n  系统时区错误"
        value: "{{ $value }}%"