groups:

- name: BPM应用宕机告警
  rules:
  - alert: BPM应用宕机告警
    expr: windows_iis_current_application_pool_state{state="Running"} == 0
    for: 1m

- name: TOMCAT错误报警
  rules:
  - alert: TOMCAT错误报警
    expr: tomcat_errorcount_total ==  0
    labels:
      severity: Informational
    annotations:
      summary: "服务器{{ $labels.Hostname }}TOMCAT报错"
      description: "Tomcat服务器报错"

- name: 实例宕机告警规则
  rules:
  - alert: 实例宕机告警
    expr: up == 0
    for: 1m
    labels:
      severity: Informational
    annotations:
      summary: "服务器{{ $labels.hostname }}宕机"
      description: " \n  Prometheus无法获取实例{{ $labels.instance }} 的监控信息! \n  请及时查看节点故障原因。\n  帮助： http://prometheus.realcan.cn:9090/targets可以查看节点连接错误信息"
      value: "UP = {{ $value }}"

- name: Linux服务器内存告警规则
  rules:
  - alert: "Linux内存告警"
    expr: (node_memory_MemTotal_bytes{mem_usage!="high"} - (node_memory_MemFree_bytes{mem_usage!="high"} + node_memory_Buffers_bytes{mem_usage!="high"} + node_memory_Cached_bytes{mem_usage!="high"} )) / node_memory_MemTotal_bytes{mem_usage!="high"} * 100 > 70
    for: 1m
    labels:
      severity: High
    annotations:
      summary: "Linux服务器{{ $labels.hostname }}内存使用率告警"
      description: "\n  Linux服务器{{ $labels.hostname }}内存使用率告警 \n  当前内存使用率为{{ $value }}% \n  服务器IP：{{ $labels.instance }} \n  所属应用：{{ $labels.APP }} \n  应用负责人：{{ $labels.manager }} \n  告警原因：内存利用率超过80%!"

- name: Linux内存占用率高告警规则
  rules:
  - alert: "SAP_linux内存告警"
    expr: (node_memory_MemTotal_bytes{mem_usage="high"} - (node_memory_MemFree_bytes{mem_usage="high"}+node_memory_Buffers_bytes{mem_usage="high"}+node_memory_Cached_bytes{mem_usage="high"} )) / node_memory_MemTotal_bytes{mem_usage="high"} * 100 > 97
    for: 1m
    labels:
      severity: Critical
    annotations:
      summary: "Linux服务器{{ $labels.hostname }}内存使用率告警"
      description: "\n  Linux服务器{{ $labels.hostname }}内存使用率告警 \n  当前内存使用率为{{ $value }}% \n  服务器IP：{{ $labels.instance }} \n  所属应用：{{ $labels.APP }} \n  应用负责人：{{ $labels.manager }} \n  告警原因：内存利用率超过80%! \n  备注：此服务器内存占用率长期超过90%，并且内存占用稳定"
      value: "{{ $value }}%"

- name: Linux CPU报警规则
  rules:
  - alert: CPU使用率告警
    expr: 100 - (avg by (instance)(irate(node_cpu_seconds_total{mode="idle"}[1m]) )) * 100 > 85
    for: 1m
    labels:
      severity: Moderate
    annotations:
      description: "\n  Linux服务器{{ $labels.hostname }}CPU使用率告警 \n  当前1分钟内CPU平均使用率为{{ $value }}% \n  服务器IP：{{ $labels.instance }} \n  所属应用：{{ $labels.APP }} \n  应用负责人：{{ $labels.manager }} \n  告警原因：1分钟内CPU平均利用率超过85%!"
      summary: "Linux服务器{{ $labels.hostname }} CPU使用率告警"
      value: "{{ $value }}%"

- name: Linux磁盘告警规则
  rules:
  - alert: Linux磁盘使用率告警
    expr: (node_filesystem_size_bytes - node_filesystem_avail_bytes) / node_filesystem_size_bytes * 100 > 90 and (node_filesystem_avail_bytes / (50 * 1024 * 1024 * 1024)) < 1
    for: 1m
    labels:
      severity: High
    annotations:
      summary: "Linux服务器{{ $labels.hostname }}磁盘使用率告警"
      description: " \n  Linux服务器{{ $labels.hostname }}磁盘使用率告警 \n  服务器IP: {{ $labels.instance }} \n  所属应用：{{ $labels.APP }} \n  应用负责人：{{ $labels.manager }} \n  告警磁盘：{{ $labels.mountpoint }} \n  当前磁盘利用率：{{ $value }}\n  磁盘使用率超过90%！且剩余空间不足50G！"


- name: Windows CPU报警规则
  rules:
  - alert: WindowsCPU告警
    expr: 100 - (avg by (instance)(irate(node_cpu_seconds_total{mode="idle"}[1m]) )) * 100 > 85
    for: 1m
    labels:
      severity: High
    annotations:
      summary: "Windows服务器{{ $labels.hostname }}CPU使用率告警！"
      description: "\n  Windows服务器{{ $labels.hostname }}CPU使用率告警 \n  CPU当前使用率：{{ $value }}\n  服务器IP: {{ $labels.instance }} \n  所属应用：{{ $labels.APP }} \n  应用负责人：{{ $labels.manager }} \n  告警原因：CPU使用率超过85%！"
      value: "{{ $value }}%"

- name: Windows 内存告警规则
  rules:
  - alert: Windows内存告警
    expr: 100.0 - 100 * windows_os_physical_memory_free_bytes / windows_cs_physical_memory_bytes > 90
    for: 1m
    labels:
      severity: High
    annotations:
      summary: "Windows服务器{{ $labels.hostname }}内存使用率告警"
      description: "\n  Windows服务器{{ $labels.hostname }}内存使用率告警 \n  内存当前使用率：{{ $value }} \n  服务器IP: {{ $labels.instance }} \n  所属应用：{{ $labels.APP }} \n  应用负责人：{{ $labels.manager }} \n  告警原因：内存利用率大于90%！"
      value: "{{ $value }}%"

- name: Windows磁盘报警规则
  rules:
  - alert: Windows磁盘告警
    expr: (1-windows_logical_disk_free_bytes/windows_logical_disk_size_bytes)*100  > 90 and   (windows_logical_disk_free_bytes / (50 * 1024 * 1024 * 1024)) < 1
    for: 1m
    labels:
      severity: High
    annotations:
      summary: "Windows服务器{{ $labels.hostname }}磁盘使用率告警"
      description: "\n  主机名:{{ $labels.hostname }} \n  IP: {{ $labels.instance }} \n 告警磁盘：{{ $labels.volume }}盘 \n  所属应用: {{ $labels.APP }} \n  应用负责人：{{ $labels.manager }} \n 告警原因：磁盘使用率超过90%!且剩余容量小于50G!"
      value: "{{ $value }}%"

- name: Oracle表空间使用率告警
  rules:
  - alert: Oracle表空间告警
    expr: oracledb_realcan_tablespace_all_shiyonglv{tablespacename!~".*TEMP"} > 95
    for: 1m
    labels:
      severity: High
    annotations:
      summary: "Oracle数据库{{ $labels.dbname }}表空间告警"
      description: "\n  数据库:{{ $labels.dbname }} \n  表空间:{{ $labels.tablespacename }} \n  已分配空间：{{ $labels.yifenpei }}G \n  最大空间：{{ $labels.zuidakongjian }}G \n  服务器IP：{{ $labels.ipaddr }} \n  告警原因：表空间{{ $labels.tablespacename }}使用率超过95%！"
      value: "{{ $value }}%"