groups:
- name: Windows告警规则
  rules:
    - alert: 收集Windows指标错误
      expr: windows_exporter_collector_success == 0
      for: 5m
      labels:
        severity: Informational
      annotations:
        summary: "服务器{{ $labels.hostname }}收集 {{ $labels.collector }} 指标失败"
        description: "CPU iowait超过阈值！"
        value: "{{ $value }}%"
    - alert: Windows服务错误
      expr: windows_service_status{status="ok"} != 1
      for: 5m
      labels:
        severity: Critical
      annotations:
        summary: "服务器{{ $labels.hostname }}Windows服务异常"
        description: "Windows 服务异常"
        value: "{{ $value }}"
    - alert: 磁盘使用率超过95%，并可用容量低于50GB
      expr: 100.0 - 100 * ((windows_logical_disk_free_bytes / 1024 / 1024 ) / (windows_logical_disk_size_bytes / 1024 / 1024)) >= 90 and (windows_logical_disk_free_bytes < (50*1024*1024*1024))
      for: 1m
      labels:
        severity: Critical
      annotations:
        summary: "服务器{{ $labels.hostname }}磁盘使用率告警"
        description: "\n  服务器{{ $labels.hostname }}磁盘使用率告警 \n  服务器IP: {{ $labels.instance }} \n  所属应用：{{ $labels.APP }} \n  应用负责人：{{ $labels.manager }} \n  磁盘使用率超过90%，并可用容量低于50GB"
        value: "{{ $value }}"
    - alert: CPU占用率超过70%告警
      expr: 100 - (avg by (instance) (rate(windows_cpu_time_total{mode="idle"}[2m])) * 100) >= 70
      for: 3m
      labels:
        severity: Moderate
      annotations:
        summary: "服务器{{ $labels.hostname }}CPU使用率告警"
        description: "\n  服务器{{ $labels.hostname }}CPU使用率告警 \n  服务器IP: {{ $labels.instance }} \n  所属应用：{{ $labels.APP }} \n  应用负责人：{{ $labels.manager }} \n  CPU占用率超过70%告警"
        value: "{{ $value }}%"
    - alert: 内存占用率
      expr: 100 - ((windows_os_physical_memory_free_bytes / windows_cs_physical_memory_bytes) * 100) >= 90
      for: 1m
      labels:
        severity: High
      annotations:
        summary: "服务器{{ $labels.hostname }}内存使用率告警"
        description: "\n  服务器{{ $labels.hostname }}内存使用率告警 \n  服务器IP: {{ $labels.instance }} \n  所属应用：{{ $labels.APP }} \n  应用负责人：{{ $labels.manager }} \n  内存占用率"
        value: "{{ $value }}%"
    - alert: 缓存使用率
      expr: (1- windows_os_virtual_memory_free_bytes / windows_os_virtual_memory_bytes) * 100 >= 50
      for: 1m
      labels:
        severity: Low
      annotations:
        summary: "服务器{{ $labels.hostname }}虚拟内存使用率告警"
        description: "\n  服务器{{ $labels.hostname }}虚拟内存使用率告警 \n  服务器IP: {{ $labels.instance }} \n  所属应用：{{ $labels.APP }} \n  应用负责人：{{ $labels.manager }} \n  缓存使用率"
        value: "{{ $value }}%"
    - alert: 主机发生重启
      expr: (time() - windows_system_system_up_time)/60 <= 10
      for: 1m
      labels:
        severity: High
      annotations:
        summary: "服务器{{ $labels.hostname }}发生重启"
        description: "\n  服务器{{ $labels.hostname }}服务器重启告警 \n  服务器IP: {{ $labels.instance }} \n  所属应用：{{ $labels.APP }} \n  应用负责人：{{ $labels.manager }} \n  主机发生重启"
        value: "{{ $value }}%"
    - alert: 系统时间不准确
      expr: (time() - windows_os_time) >= 60
      for: 1m
      labels:
        severity: High
      annotations:
        summary: "服务器{{ $labels.hostname }}系统时间不准确"
        description: "\n  服务器{{ $labels.hostname }}系统时间告警 \n  服务器IP: {{ $labels.instance }} \n  所属应用：{{ $labels.APP }} \n  应用负责人：{{ $labels.manager }} \n  系统时间不准确"
        value: "{{ $value }}%"
    - alert: 网络利用率超过
      expr: sum by (instance) (rate(windows_net_bytes_received_total[2m])) / 1024 / 1024 > 100 or sum by (instance) (rate(windows_net_bytes_sent_total[2m])) / 1024 / 1024 > 100
      for: 1m
      labels:
        severity: Moderateh
      annotations:
        summary: "服务器{{ $labels.hostname }}网络利用率超过100Mbps"
        description: "\n  服务器{{ $labels.hostname }}网络使用率告警 \n  服务器IP: {{ $labels.instance }} \n  所属应用：{{ $labels.APP }} \n  应用负责人：{{ $labels.manager }} \n  网络利用率超过"
        value: "{{ $value }}%"
    - alert: 网络接口错误率超过阈值
      expr: 100 * rate(windows_net_packets_received_errors[5m]) / (rate(windows_net_packets_received_errors[5m]) + rate(windows_net_packets_received_total[5m])>0)  > 75 or 100 * rate(windows_net_packets_outbound_errors[5m]) / (rate(windows_net_packets_outbound_errors[5m]) + rate(windows_net_packets_sent_total[5m])>0)  > 75
      for: 1m
      labels:
        severity: High
      annotations:
        summary: "服务器{{ $labels.hostname }}网络接口出现错误包"
        description: "\n  服务器{{ $labels.hostname }}网络接库错误率告警 \n  服务器IP: {{ $labels.instance }} \n  所属应用：{{ $labels.APP }} \n  应用负责人：{{ $labels.manager }} \n  网络接口错误率超过阈值"
        value: "{{ $value }}%"
    - alert: 网络接口发生变化
      expr: changes(windows_net_current_bandwidth_bytes[10m]) > 0
      for: 1m
      labels:
        severity: High
      annotations:
        summary: "服务器{{ $labels.hostname }}网络接口发生变化"
        description: "\n  服务器{{ $labels.hostname }}网络接口告警 \n  服务器IP: {{ $labels.instance }} \n  所属应用：{{ $labels.APP }} \n  应用负责人：{{ $labels.manager }} \n  网络接口发生变化"
        value: "{{ $value }}%"
    - alert: 系统时区错误
      expr: sum by(instance) (windows_os_timezone{time_zone="CST"}) != 1
      for: 1m
      labels:
        severity: High
      annotations:
        summary: "服务器{{ $labels.hostname }}系统时区错误"
        description: "\n  服务器{{ $labels.hostname }}系统时区告警 \n  服务器IP: {{ $labels.instance }} \n  所属应用：{{ $labels.APP }} \n  应用负责人：{{ $labels.manager }} \n  系统时区错误"
        value: "{{ $value }}%"